### ISSUE TITLE
use relative paths

### ISSUE THREAD

**Issue by jillesca** [bdolenc/ll-test#1]
When creating directories or files, use relative paths to reduce the changes the user creates the directory/file in the wrong 

Consider using the ncs env vars too, so users are more familiar with them

```
NCS_DIR=/opt/ncs/current
NCS_CONFIG_DIR=/etc/ncs
NCS_LOG_DIR=/log
NCS_RUN_DIR=/nso/run
```

**Comment by jillesca** [comment]
When copying a file use relative paths or env vars as well. if the command is too long, maybe change directory first and the copy, but give the user the context of where the operations are happening.

**Comment by bdolenc** [comment]
Using relative paths where applicable now.
