### ISSUE TITLE
white space breaks make

### ISSUE THREAD

**Issue by jillesca** [bdolenc/ll-test#11]
the final make example in https://github.com/bdolenc/ll-test#system-testing-and-storing-expected-configuration has a white space which breaks make

```
test:
    $(MAKE) remove-loopback
	$(MAKE) configure-loopback
```

**Comment by jillesca** [comment]
Add a comment that a white space can break make and how to fix it, in vscode there is an option to convert spaces to tab

**Comment by bdolenc** [comment]
Removed the whitespace. Added a note that tabs need to be used as delimiters and how to convert with vscode.
