### ISSUE TITLE
loopback python example

### ISSUE THREAD

**Issue by jillesca** [bdolenc/ll-test#5]
probably is worth that the readme example on https://github.com/bdolenc/ll-test#loopback-python-example is the same from the beginning as https://github.com/bdolenc/ll-test/blob/main/loopback/python/loopback/loopback.py 

I'm not sure however if there is a need for having a different example from the beginning. 

Use relative paths when referring to directories and files

> Replace the ServiceCallbacks class in loopback/python/loopback/loopback.py with the snippet bellow and edit it according to instructions bellow.

Additionally, there is a repeated import statement here

```
python3
import ipaddress
import ipaddress
net = ipaddress.IPv4Network('10.0.0.0/8')
list(net.hosts())[0] 
```

**Comment by bdolenc** [comment]
Using the same example from the start now. Fixed duplicated import.
